# Site settings
title: Grupo de Desarrolladores Scala Chile
email: contacto@scala-lang.cl
description: Grupo abierto de Desarrolladores que tiene el objetivo de promover el uso del lenguaje de progamación Scala en Chile y América Latina.
baseurl: '/'
url: http://scala-lang.cl

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif
gauges_id: 503c5af6613f5d0f19000027
repository: https://github.com/driquelme/driquelme.github.io
google_analytics_id: UA-50781869-1

